02 MVC.Model/Controllers/CartController.cs
using _02_MVC.Model.Helper;
using BusinessLogic.Interfaces;
using BusinessLogic.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace _02_MVC.Model.Controllers
{
	public class CartController : Controller
	{
        private readonly ICartService cartService;

        public CartController(ICartService cartService)
        {
            this.cartService = cartService;
        }

        public IActionResult Index(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View(cartService.GetProducts());
        }

        public IActionResult Add(int id, string returnUrl)
        {
            cartService.Add(id);

            return Redirect(returnUrl);
        }

        public IActionResult Remove(int id, string returnUrl)
        {
            cartService.Delete(id);

            return Redirect(returnUrl);
        }
    }
}

02 MVC.Model/Controllers/OrdersController.cs
using BusinessLogic.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace _02_MVC.Model.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IOrdersService ordersService;
        private string UserId => User.FindFirstValue(ClaimTypes.NameIdentifier)!;

        public OrdersController(IOrdersService ordersService)
        {
            this.ordersService = ordersService;
        }
        public IActionResult Index()
        {
            return View(ordersService.GetAllByUser(UserId));
        }

        public IActionResult Create()
        {
            ordersService.Create(UserId);
            return RedirectToAction(nameof(Index));
        }
    }
}

02 MVC.Model/Controllers/ProductsController.cs
using AutoMapper;
using BusinessLogic.DTOs;
using BusinessLogic.Interfaces;
using BusinessLogic.Services;
using DataAccess.Model.Data;
using DataAccess.Model.Data.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Model.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProductsController : Controller
    {
        private readonly IProductsService productService;
        private readonly IMapper mapper;

        public ProductsController(IProductsService productService, IMapper mapper)
        {
            this.productService = productService;
            this.mapper = mapper;
        }
		private void LoadCategories()
		{
            var categories = productService.GetAllCategories();
            ViewBag.Categories = new SelectList(categories, nameof(Category.Id), nameof(Category.Name));
		}
        [AllowAnonymous]
        public IActionResult Index()
        {
            return View(productService.GetAll());
        }
        [AllowAnonymous]
        public IActionResult Description()
        {
            return View();
        }
        
        public IActionResult Create()
        {
			LoadCategories();
			return View();
        }
        [HttpPost]
        public IActionResult Create(ProductDto model)
		{
			if (!ModelState.IsValid)
			{
				LoadCategories();
				return View();
			}


            productService.Create(model);
			return RedirectToAction(nameof(Index));
		}
        [AllowAnonymous]
        public IActionResult Details(int id, string? returnUrl)
		{
            var product = productService.Get(id);
			if (product == null) return NotFound();
            ViewBag.ReturnUrl = returnUrl;
            return View(product);
		}
        public IActionResult Edit(int id)
        {
            var product = productService.Get(id);
            if (product == null) return NotFound();
            LoadCategories();
            return View(mapper.Map<ProductDto>(product));
        }
        [HttpPost]
        public IActionResult Edit(ProductDto model)
        {
            if (!ModelState.IsValid)
            {
                LoadCategories();
                return View();
            }

            productService.Edit(model);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Delete(int id)
		{
            productService.Delete(id);
			return RedirectToAction(nameof(Index));
		}
	}
}

02 MVC.Model/Views/Cart/Index.cshtml
@model List<ProductDto>;

<table class="table table-striped">
	<thead>
		<tr>
			<th class="text-white" scope="col">#</th>
			<th class="text-white" scope="col">Image</th>
			<th class="text-white" scope="col">Name</th>
			<th class="text-white" scope="col">Price</th>
			<th class="text-white" scope="col">Category</th>
			<th class="text-white" scope="col">Discount</th>
			<th class="text-white" scope="col">Actions</th>
		</tr>
	</thead>
	<tbody>
		@foreach(var i in Model)
		{
			<tr class="align-middle">
				<th class="text-white" scope="row">@i.Id</th>
				<th scope="row">
					<img height="40" class="rounded-2 zoom" src="@i.ImageUrl" alt="@i.Name" />
				</th>
				<td class="text-white">
					<a asp-controller="Products" asp-action="Details" class="cart-item" asp-route-id="@i.Id" asp-route-returnUrl="@Context.Request.Path">@i.Name</a>
					@if (i.Discount > 0)
					{
						<span class="badge bg-danger text-black">SALE</span>
					}
				</td>
				<td class="text-white">@i.Price$</td>
				<td class="text-white">@i.CategoryName</td>
				<td class="text-white">@i.Discount%</td>
				<td>
					<div class="btn-group" role="group" aria-label="Basic example">
						<a class="btn btn-danger" asp-controller="Cart" asp-action="Delete" asp-route-id="@i.Id">
							<i class="bi bi-trash3-fill"></i>
						</a>
					</div>
				</td>
			</tr>
		}
	</tbody>
</table>
<div>
	<a asp-controller="Orders" asp-action="Create" class="btn btn-danger mt-3">Make an order</a>
</div>

<p>Items: @Model.Count</p>